sudo: required
language: ruby
node_js:
- '2.2'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: UzsLCbolnT20oXQf+R5T7JEWpS1G0VUTwO2Vv79ne8+wiRrFPUxvkfQ8cK8uQXs3vb7hbIKz3ME3vLMf9bPr5UqmgSxWaSeWAAcdgHyNCkXApH2erFlkYe0kP6Ig+DO9/O1+E4Weth3yq/xIL3hlN8cL/uzDN0Yib+Y7kNEipQshVBv1m130gboZGpMUyGl756AdNRzhz+JQOo2TnbsfetOYwI/3+uGq84Mpe2gLkhBsFknDisz7XRS2I854qTOZq5P4jhEcfZ5KgaxuRHzwHwBQ7RG4VAbQnx9lk6CXE2TI0NJ4kIyTaE4BKNRoQOii7op5n9O92YctB2yuo6ouzTp6C3fi1lecl3MneEQJEcBz/jR5HBIR5uzaQvaU4Y9vC3/sm+IJQLtbqM7JkfLiGm5nVybiYbkpYhbM7tyilFGi3OnXOVtOB3hED9TrwEtuReuFgUGzIYaKtUXpZpIH0WuAi6ItcWGbPtK7LTkxeHKr1HAez9H2M/GMLpaDNYZZrYhIfNv4zGrWadHeh8xoW+3SovjynM2gWloPCFPXaVdtQnNDQ6pjZKs1nKtuUIdH3dFE8Z8FyBby0AhNimRF8RD6BPE02BBHiHI063L4Ady/SQeNzpY5Q3Wqdw+WFq9NgPlQ3Fq/eH7LHz+rLxCqcHPeYj26zQSHkFTiBouXrYM=
  - secure: mXj6+vO21CmRYoaT1nyAIUIzX58pBa8uotAT/oIZtxPymbQWxiYriNwoZQQz6Q2znjwutNiTQwREO4ORoasLcsuvV5GeEzH+WJs+kT5+6R/JJH1VVIj5xD2qU5uV253f2C+CcxvsRaDYk1tp03OAL3JZPc2s1BJlGrO/dtqJCSAikfheXy2/6YvU0uTcVlVWU7LfKDPJy/m4sAtIlhE202ZaSVkCHe9DaTx+jp7cBlIXeZXWcXkYEIGod8ED3fr2WrQy5zlIg1POOtMOYXBai5Ljg/vawWKrB7rvw9bVBwG8maN+fcIl3Pqz/behsTJ5M3AH+5LKR3p1Um/fjSlqOTf4jGiFRjfsbTBCZVu3UIpIZO/1PvyIEa0t5h+AQ/O50mbtSgu8EmwmrLOdqjgplFKNAWTtjVIzkVrP758xl//AvoBXugD1Inu2lBih6I/TzD/XO1/QxkZIV4Ztk8gn9bxoPRyeasmdC2gT3PmMuRT0AuUwDVXPqNUcJFHqsfa55JKem+WX2ufHgHbrL8HcMVPTRdYreEniN0FiYlWZa/rukqQrsOXXOh3VdRdlbDhbQoRXj5kBTMAMg9/Rwy84HMK6c3ZLDd7sqb8mZMZIxp3XobIR2WJpDeGO0vNpvOA9N1RU/jE+P1cgrsXTGUHj0qrfEAT4ID4bMHmYoeRjS/U=
  - secure: HzEFpXv1IE3LxoF4Ow3z9boBmmNo3tZtb1B5Am0/u2MyIEywGcU8cTrvTO/pl3a/l3sBtxhmj2L93PGoEv47uDhKlAEPCHSk4ppWv7DKVjXVWkQS6HHSnlAZf1no0vAZU8rPYufw/dgeI8bmF00Wp/MHu/vlTNyj2zzi2NjLIe7OV3wmhAPjDrQ2YczgTQA6HfTL80oU+mZ8/cIZv8icQ3bI0mTS21A/fYggxlP+oUpnR2a2gQq2WGNpAhK+ggEqXdEeAJxZOsxqRDC1UGGti7vKGfuZ2RU/KBU2hHq1qjkgIWxkaN+0ZZtvwjkyEOROfviv1uBmGC8O8szDdU5ZviTAuRai/r7RqxA8GhDbWt7Fq0LyVYGSC2XngLfEr7jndKQtfFkLANM9XiQDdu+QL8zPnWXBZtgDhMEYTYbdGHrscW73zaMX6W9x+JBWLoS64RqwbZPCwLCSRjRbjmVG590KhEZ8g2pgGXZ8JeZlteh2is05b9XYmPlflzthTlXTuhUYC7Mo3te1nEFogkSn1EgX67hZc0EwHBv9O5a+iMJaKuXb5QAVNE8bYsCRTusF/RUeIuzQ69ncqTxQtYR7fsiO0H3pNUxpGler3qR50yyz6NgsdxJIKSMYXt+1Jlili7BBBxqIzugyh1SvdYToef4i32tzi5mf38qTYgg/+pA=
script:
- echo 'tested'
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export DEPLOYMENT_IMAGE=codeforruhrgebiet/kpis
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $DEPLOYMENT_IMAGE:$COMMIT .
- docker tag $DEPLOYMENT_IMAGE:$COMMIT $DEPLOYMENT_IMAGE:$TAG
- docker tag $DEPLOYMENT_IMAGE:$COMMIT $DEPLOYMENT_IMAGE:travis-$TRAVIS_BUILD_NUMBER
- docker push $DEPLOYMENT_IMAGE
